### PR TITLE
Hide API key

### PR DESCRIPTION
**Pull request by dansjack**
## Summary
Hides the api key for the census bureau from GitHub and ensure that the CircleCI builds and coverage reports don't fail by adding an environment variable to CircleCI

To test:
1. Go to the [Offboarding folder](https://drive.google.com/drive/folders/1hGCHGhtyWEKmahNxUKdZQ1Ra4ND-2WuD) and download `apikeys.properties`
2. Add `apikeys.properties` to the root of the project
3. Select a new location and get a snapshot to ensure the api key is working correctly. 

## Checklist
- [ ] New tests added to account for changes in this MR
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Review by AllisonBC — DISMISSED** [review]
Nice, works as described! Maybe you could delete that last rogue TODO comment in the strings resource file before you merge

**Comment by dansjack** [comment]
> Nice, works as described! Maybe you could delete that last rogue TODO comment in the strings resource file before you merge

@AllisonBC good call, done!

**Review by unicornsleuth — APPROVED** [review]
Everything looks great! Awesome job  : ))

**Review by AllisonBC — APPROVED** [review]
Approved

**Pull request merged**
