### PR TITLE
Move API Calls and some cleanup

### LINKED ISSUE #51: Move API Calls to ViewModel
### User Story
As a dev, I want to put the API calls in our ViewModel, so the calls are more accessible throughout the app.

### Acceptance Criteria
- [x] makeApiCalls() moved from LocationManualSelectFragment to ViewModel
- [x] The app works as it did before

### PR DESCRIPTION
**Pull request by dansjack**
## Summary
Closes #51 

This PR does the following:
* Moves makeApiCalls to the ViewModel
* Cleans up a bunch of code we didn't need anymore after moving makeApiCalls
* Updates the final api call that wasn't to v3 of the disease.sh api
* Capitalizes counties in the dropdown menu
* Capitalizes state and county name in the RiskDetailPageFragment
* Changes the state and county name in RiskDetailPageFragment to wrap when the names are long
* Updates the RiskDetailPageFragment spacing so part of the card layout isn't cut off by the last updated text at the bottom (e.g. Pixel 2)

~~🚨 I need to look at how this affects existing tests and also see why the app is making API calls each time the app is stopped and re-opened (if a saved snapshot exists) 🚨~~

Updated tests to account for changes and figured out why the API calls were always being called.

## Checklist
- [ ] New tests added to account for changes in this MR
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Comment by unicornsleuth** [comment]
I just pulled this up on my computer, and after an uninstall, it shows Imperial, California risk detail. So I think that is running automatically on app start?

**Comment by dansjack** [comment]
> I just pulled this up on my computer, and after an uninstall, it shows Imperial, California risk detail. So I think that is running automatically on app start?

@unicornsleuth hmm I can't reproduce this, it shows the location selection fragment for me. Are you sure you didn't run an activity test instead? Imperial California is the location for one of the tests.

**Comment by unicornsleuth** [comment]
Uhhhh that may be what happened! I went back to your branch and tried again and it works perfectly lol. I'll do the review now.

**Review by unicornsleuth — APPROVED** [review]
Excellent! Still works very well!

**Comment by AllisonBC** [comment]
Is this the cutoff you are referring to in the last bulleted change? ("Updates the RiskDetailPageFragment spacing so part of the card layout isn't cut off by the last updated text at the bottom (e.g. Pixel 2)")

Attached photo
image

**Comment by unicornsleuth** [comment]
@AllisonBC No, that's a separate issue that I don't know how to fix! Dan fixed the issue where when scrolled to the bottom, the "last updated" bar covers the bottom of the risk details

**Review by AllisonBC — APPROVED** [review]
The many fixes are fixed as described. Nice job!

**Pull request merged**
