### PR TITLE
Add About fragment

### LINKED ISSUE #41: Add About page
### User Story
As a user, I want to see more information about the app, including version number and how risk is calculated, so I can better understand the app I'm using. 

### Additional Context
The about page was specifically requested by the client

### Acceptance Criteria
- [x] There is an about page that the user can navigate to

### PR DESCRIPTION
**Pull request by dansjack**
## Summary
Closes #41 

This PR adds an About page Fragment and a method in the MainActivity to instantiate it.
* Adds @unicornsleuth's explanation of risk in an expandable TextView. The Expandable TextView comes from [this article](https://medium.com/@yuriyskul/expandable-textview-using-staticlayouts-data-f9bc9cbdf283)
* Adds bullets to expand on the sources of data from Disease.sh

The fragment is currently detached from the rest of the UI, but to test, you can call `openAboutFragment()` within the `loadFragments()` method in `MainActivity`. Once we add this fragment to the rest of the UI, I'll write tests for it.

_Unexpanded_
image

_Expanded_
image

You should be able to:
- [ ] Expand and collapse the TextView under Determining Risk
- [ ] Click any of the links on the page
- [ ] Scroll up and down

## Checklist
- [ ] New tests added to account for changes in this MR
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Comment by dansjack** [comment]
Canceled latest workflow to save a FTL test run, the only change in the last commit was to center the **About The App** heading

**Comment by chonger878** [comment]
Sorry, but the app crashed.  I am not sure if it was on my end or not...

**Comment by dansjack** [comment]
> Sorry, but the app crashed. I am not sure if it was on my end or not...

Hmm I just tested it again and it should be fine. Maybe you brought over some uncommitted changes from your branch when you checked out mine?

**Review by unicornsleuth — APPROVED** [review]
Awesome! Works as expected

**Review by AllisonBC — APPROVED** [review]
Page appears as described and link is functional. I did notice that on my screen, there is a small formatting bug that isn't shown in your description image. Attached screenshot
image

**Comment by dansjack** [comment]
> Page appears as described and link is functional. I did notice that on my screen, there is a small formatting bug that isn't shown in your description image. Attached screenshot
> image

Fixed, thanks!

**Pull request merged**
