### PR TITLE
Yaholl/add room back in

### LINKED ISSUE #34: Conditionally Render Fragment based on Room
As a user, if I have already used this app, I want the app to display my most recently viewed location
As a user, if I haven't used this app yet, I want the app to prompt me to select a new location

### PR DESCRIPTION
**Pull request by unicornsleuth**
## Summary
Closes #34 

- adds locationId to county_fips & Locationj.java 
- reconnects Room, and saves each Snapshot to Room
- removes Location table entirely from Room
- adds a "loading page" with a temporary image
- when the Room listener comes back with either null or a snapshot, the correct fragment is loaded
- adds a (temporarily placed) button on the Risk Detail page to navigate back to the Location Selection page
- fixes broken tests and adds one new one

## Checklist
- [x] New tests added to account for changes in this MR
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Review by dansjack — COMMENTED** [review]
All the code looks good, that's awesome we can see the last snapshot now after loading the app! 🎉 

I tried out the following:
- [x] Select a State and County, press Submit, see results
- [x] Press Select Location, repeat the above step
- [x] Select a State and County, change orientation to landscape, press Submit, see resutls

The only issue I had was when I clicked the square navigation button on the Android device. It caused the app to crash. If you look at the log output, you'll see a stacktrace starting like this:
```java.lang.RuntimeException: Parcel: unable to marshal value Location{locationId=1, county='sebastian', state='arkansas', countyFips='05', stateFips='131'}```

image

**Review by dansjack — APPROVED** [review]
That bug is on the develop branch as well, so it's a non-blocker

**Comment by dansjack** [comment]
I found a fix! https://stackoverflow.com/questions/3818745/androidruntime-error-parcel-unable-to-marshal-value

You should just need to add `implements Serializable` to the signature of the Location class. It worked when I did it on the develop branch.

**Review by dansjack — APPROVED** [review]
That error is fixed!

A different error shows up now when pressing that square button (it takes a few seconds to show up), but I think it's still fine to merge this into `develop`. We have it documented and can figure it out later, and it's not breaking the app while we're actually using it.

image

It could be caused by the amount of data being sent with intents (see [StackOverflow](https://stackoverflow.com/questions/23407821/how-to-solve-error-failed-binder-transaction-in-android-4-4). We may need to find a way to reduce the amount of data sent through intents (the maps, specifically).

**Comment by unicornsleuth** [comment]
> 
> 
> That error is fixed!
> 
> A different error shows up now when pressing that square button (it takes a few seconds to show up), but I think it's still fine to merge this into `develop`. We have it documented and can figure it out later, and it's not breaking the app while we're actually using it.
> 
> image
> 
> It could be caused by the amount of data being sent with intents (see [StackOverflow](https://stackoverflow.com/questions/23407821/how-to-solve-error-failed-binder-transaction-in-android-4-4). We may need to find a way to reduce the amount of data sent through intents (the maps, specifically).

Yeah, I had to create a new Map in order to get location by ID, but I see why you need it to search by State as well, so I think we could just come up with another data structure that would work

**Comment by AllisonBC** [comment]
I experienced the previously described TransactionTooLarge crash as well as the screenshotted one below. Seems probable to be a comorbid type of bug with the others found to do with the map.

Error steps:
1. Select a location and submit
2. Press 'back' (to close app)
3. Reopen app

Screenshot 2020-11-01 185238

**Review by AllisonBC — APPROVED** [review]
Ready to merge to develop; looking forward to hooking up the app bar to your work. Nice job!

**Pull request merged**
