### PR TITLE
App V0.4.0

### PR DESCRIPTION
**Pull request by dansjack**
## Summary

This PR contains the following: 
* Graphs!
* Fixes capitalization of locations in risk view and counties in the county spinner
* Fixes overlap of last updated text in risk view on certain devices
* About fragment added but not displayed

## Checklist
- [ ] New tests added to account for changes in this MR
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Review by AllisonBC — APPROVED** [review]
Functionality is as described

**Review by chonger878 — COMMENTED** [review]
Hm, can't seem to access about page.  Did I miss something?

**Comment by dansjack** [comment]
> Hm, can't seem to access about page. Did I miss something?

@chonger878 
> About fragment added but not displayed 

There's no nav component so there's no way to view it in this PR

**Review by chonger878 — APPROVED** [review]
Functionality works great, especially when I try to submit without choosing state and county.  Also, when I exit and re-enter the app, the info is saved (yay!).  When I pushed the back arrow, everything is reset. Looks great in general!

**Comment by chonger878** [comment]
Oh haha, I now just noticed  in the PR notes that you remarked that the about page was not displayed.  I gotta read the notes first.

**Pull request merged**
