### PR TITLE
Yaholl/javadoc cleanup

### PR DESCRIPTION
**Pull request by unicornsleuth**
## Summary
Adds Javadoc comments

## Checklist
- [x] All tests passing locally
- [x] All tests passing on CircleCI
- [x] Assigned at least 2 reviewers

### CODE REVIEW

**Review by dansjack — APPROVED** [review]
Great javadoc comments!

**Review by chonger878 — CHANGES_REQUESTED** [review]
I have a few suggestions, but I might be overthinking things, so you can take it with a grain of salt.  For lines 246-248, perhaps instead of "sets basic data for Chart", you might just want to say "sets the axes for Chart."  I know the method says "setAxes()" but the "sets basic data for Chart" might make things confusing and inconsistent.

**Review by chonger878 — APPROVED** [review]
I probably should have mentioned other than that statement, I couldn't find any other issue with the java docs.

**Comment by dansjack** [comment]
Cleaned up two small merge conflicts where we both wrote javadocs for the same functions! I chose your javadoc comment for the `fillLocationsMap` comment and mine for the `makeApiCalls` comment.

**Pull request merged**
